package com.mayursarode.newsapp.utils

import com.mayursarode.newsapp.data.model.Country

val COUNTRIES = listOf(
    Country("ae", "United Arab Emirates"),
    Country("ar", "Argentina"),
    Country("at", "Austria"),
    Country("be", "Belgium"),
    Country("bg", "Bulgaria"),
    Country("br", "Brazil"),
    Country("ca", "Canada"),
    Country("ch", "Switzerland"),
    Country("cn", "China"),
    Country("co", "Colombia"),
    Country("cu", "Cuba"),
    Country("cz", "Czechia"),
    Country("de", "Germany"),
    Country("eg", "Egypt"),
    Country("fr", "France"),
    Country("gb", "United Kingdom of Great Britain and Northern Ireland"),
    Country("gr", "Greece"),
    Country("hk", "Hong Kong"),
    Country("hu", "Hungary"),
    Country("id", "Indonesia"),
    Country("ie", "Ireland"),
    Country("il", "Israel"),
    Country("in", "India"),
    Country("it", "Italy"),
    Country("jp", "Japan"),
    Country("kr", "Korea"),
    Country("lt", "Lithuania"),
    Country("lv", "Latvia"),
    Country("ma", "Morocco"),
    Country("mx", "Mexico"),
    Country("my", "Malaysia"),
    Country("ng", "Nigeria"),
    Country("nl", "Netherlands"),
    Country("no", "Norway"),
    Country("nz", "New Zealand"),
    Country("ph", "Philippines"),
    Country("pl", "Poland"),
    Country("pt", "Portugal"),
    Country("ro", "Romania"),
    Country("rs", "Serbia"),
    Country("ru", "Russian Federation"),
    Country("sa", "Saudi Arabia"),
    Country("se", "Sweden"),
    Country("sg", "Singapore"),
    Country("si", "Slovenia"),
    Country("sk", "Slovakia"),
    Country("th", "Thailand"),
    Country("tr", "Turkey"),
    Country("tw", "Taiwan, Province of China"),
    Country("ua", "Ukraine"),
    Country("us", "United States of America"),
    Country("ve", "Venezuela"),
    Country("za", "South Africa")
)